
export const UPDATE_EXPRESSIONS = 'UPDATE_EXPRESSIONS';
export const UPDATE_SELECTED_NOTATION = 'UPDATE_SELECTED_NOTATION';
export const UPDATE_TO_NOTATION = 'UPDATE_TO_NOTATION';
export const UDPATE_NOTATION_VALIDATION = 'UDPATE_NOTATION_VALIDATION';
