export const UPDATE_POSTFIX_EXPRESSION = 'UPDATE_POSTFIX_EXPRESSION';
export const UPDATE_INFIX_EXPRESSION = 'UPDATE_INFIX_EXPRESSION';
export const UPDATE_PREFIX_EXPRESSION = 'UPDATE_PREFIX_EXPRESSION';